# Project information
site_name: Voxel Tycoon Modding Documentation
site_description: Lean how to mod Voxel Tycoon — a tycoon strategy game about transportation, factories, and mining infinite voxel landscapes.
site_author: Voxel Tycoon Devs
site_url: https://docs.voxeltycoon.xyz

# Repository
repo_name: voxeltycoon/docs
repo_url: https://github.com/voxeltycoon/docs

# Copyright
copyright: Copyright &copy; 2016 - 2021 Voxel Tycoon Devs

# Configuration
theme:
  name: material
  language: en
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  features:
  - navigation.tabs
  - navigation.indexes
  - content.code.copy
  - content.code.annotate

extra_css:
  - stylesheets/extra.css

# Extras
extra:
  analytics:
    provider: google
    property: UA-37507673-9
  social:
    - icon: fontawesome/brands/steam
      link: https://voxeltycoon.xyz/buy
    - icon: fontawesome/brands/discord
      link: https://discord.gg/voxeltycoon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/voxeltycoon
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/voxeltycoon
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/voxeltycoon

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized
  - awesome-pages

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.keys